import { useEffect, useMemo, useRef, useState } from "react";
import { Background, Controls, Handle, MiniMap, Position, ReactFlow, SelectionMode, useNodesState, type Connection, type Node } from "@xyflow/react";
import { ArrowSquareOut, Copy, DownloadSimple, ImageSquare, PencilSimple, Plus, Selection, TextT, Trash, Play, FloppyDisk } from "@phosphor-icons/react";
import { useStore } from "./store";
import type { CanvasNode, TaskNode } from "./types";

const ratios=[['auto','自适应'],['1:1','方形 1:1'],['3:4','竖向 3:4'],['9:16','竖向 9:16'],['16:9','横向 16:9']];
const statusLabel:Record<string,string>={idle:'尚未运行',queued:'排队中',waiting_page:'等待页面',uploading:'上传中',sending:'发送中',generating:'生成中',completed:'已完成',failed:'运行失败',manual_action:'需要手动处理'};

function TaskCard({data}:{data:{node:TaskNode,projectId:string,inputs:number}}){const s=useStore();const n=data.node;return <article className={`task-card status-${n.status}`}>
  <Handle type="target" position={Position.Left} className="node-handle"/><header><strong>{n.name}</strong><label>图像比例<select value={n.aspectRatio??'auto'} onChange={e=>s.updateNode(n.id,{aspectRatio:e.target.value} as Partial<TaskNode>)}>{ratios.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><span data-status={n.status}>{statusLabel[n.status]}</span></header>
  <div className="task-inputs"><p><ImageSquare/> 已连接参考图 <b>{data.inputs}</b> 张</p>{!data.inputs&&<small>从外部图片或文字节点连线进入</small>}</div>
  {n.statusDetail&&<p className="status-detail">{n.statusDetail}</p>}<textarea value={n.prompt} placeholder="在这里描述你想生成的内容" onChange={e=>s.updateNode(n.id,{prompt:e.target.value} as Partial<TaskNode>)}/>
  <footer><div><button title="复制任务" onClick={()=>s.duplicateTask(n.id)}><Copy/></button><button title="打开真实对话" onClick={()=>s.openTask(n.id)}><ArrowSquareOut/></button><button title="删除任务" onClick={()=>{s.setSelected([n.id]);void s.deleteSelected()}}><Trash/></button></div><small>上下文 {n.runCount??0} 轮</small><button className="run" disabled={['queued','sending','generating'].includes(n.status)} onClick={()=>s.runTask(n.id)}><Play weight="fill"/>{['queued','sending','generating'].includes(n.status)?statusLabel[n.status]:'运行任务'}</button></footer><Handle type="source" position={Position.Right} className="node-handle"/>
  </article>}
function TextCard({data}:{data:{node:Extract<CanvasNode,{kind:'text'}>}}){const s=useStore();return <div className="text-card"><Handle type="source" position={Position.Right} className="node-handle"/><label>文字提示</label><textarea value={data.node.text} placeholder="输入可复用的提示词" onChange={e=>s.updateNode(data.node.id,{text:e.target.value} as Partial<CanvasNode>)}/></div>}
function MediaCard({data}:{data:{node:Extract<CanvasNode,{kind:'image'|'result'}>,url?:string}}){return <div className="media-card"><Handle type="source" position={Position.Right} className="node-handle"/><label>{data.node.kind==='result'?'生成结果':data.node.title}</label>{data.url?<img src={data.url}/>:<span>图片载入中</span>}</div>}
function TextResultCard({data}:{data:{node:Extract<CanvasNode,{kind:'text_result'}>}}){return <div className="text-result-card"><label>文字结果</label><textarea readOnly value={data.node.text}/><Handle type="source" position={Position.Right} className="node-handle"/></div>}
const nodeTypes={task:TaskCard,text:TextCard,image:MediaCard,result:MediaCard,text_result:TextResultCard};

export function App(){const s=useStore();const file=useRef<HTMLInputElement>(null);const [notice,setNotice]=useState('');useEffect(()=>{void s.initialize()},[]);const storedNodes=useMemo<Node[]>(()=>s.project?.graph.nodes.map(n=>({id:n.id,type:n.kind,position:n.position,initialWidth:n.kind==='task'?328:n.kind==='text_result'?360:n.kind==='text'?270:320,initialHeight:n.kind==='task'?224:n.kind==='text_result'?220:n.kind==='text'?140:260,data:{node:n,projectId:s.project!.id,url:(n.kind==='image'||n.kind==='result')?s.assets[n.assetId]:undefined,inputs:n.kind==='task'?s.project!.graph.edges.filter(e=>e.target===n.id&&e.kind!=='output').length:0},selected:s.selected.includes(n.id)}))??[],[s.project,s.assets,s.selected]);const [nodes,setNodes,applyNodeChanges]=useNodesState<Node>(storedNodes);useEffect(()=>{setNodes(current=>storedNodes.map(next=>{const previous=current.find(node=>node.id===next.id);return previous?.dragging?{...next,position:previous.position,dragging:true,measured:previous.measured}:{...next,measured:previous?.measured}}))},[storedNodes,setNodes]);const edges=useMemo(()=>s.project?.graph.edges.map(e=>({id:e.id,source:e.source,target:e.target,animated:e.kind==='output',style:{stroke:'#6f3cff',strokeWidth:2}}))??[],[s.project]);
  if(!s.ready||!s.project)return <div className="loading">正在打开 Pixel Flow</div>;
  const center={x:620,y:220};return <main className="app" tabIndex={-1} onKeyDown={e=>{if((e.key==='Backspace'||e.key==='Delete')&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();void s.deleteSelected()}}}>
    <header className="topbar"><div className="brand"><span>PF</span><div><strong>Pixel Flow</strong><small>AI 创意任务画布</small></div></div><div className="project"><select value={s.project.id} onChange={e=>s.openProject(e.target.value)}>{s.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button title="新建画布" onClick={()=>s.createProject()}><Plus/></button><button title="重命名画布" onClick={()=>s.renameProject()}><PencilSimple/></button></div><div className="top-actions"><span><i/>本地画布已连接</span><button onClick={async()=>{setNotice(`已释放 ${await s.hibernate()} 个网页标签`);setTimeout(()=>setNotice(''),2500)}}>节省内存</button><button title="备份画布" onClick={()=>s.backup()}><FloppyDisk/></button>{notice&&<em>{notice}</em>}</div></header>
    <nav className="toolbar"><button className="active" title="选择与移动"><Selection/></button><button title="上传图像" onClick={()=>file.current?.click()}><ImageSquare/></button><button title="新增文字" onClick={()=>s.addText(center)}><TextT/></button><button title="新增任务" onClick={()=>s.addTask(center)}><Plus/></button><input ref={file} type="file" accept="image/*" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void s.addImage(f,{x:100,y:180});e.currentTarget.value=''}}/></nav>
    <section className="stage"><ReactFlow nodeTypes={nodeTypes} nodes={nodes} edges={edges} onConnect={(c:Connection)=>c.source&&c.target&&s.connect(c.source,c.target)} onNodesChange={(changes)=>{applyNodeChanges(changes);const selected=new Set(s.selected);let selectionChanged=false;for(const c of changes){if(c.type==='select'){selectionChanged=true;c.selected?selected.add(c.id):selected.delete(c.id)}if(c.type==='position'&&c.position&&!c.dragging)void s.moveNode(c.id,c.position)}if(selectionChanged)s.setSelected([...selected])}} fitView fitViewOptions={{padding:.18,maxZoom:1}} minZoom={.15} maxZoom={2} deleteKeyCode={null} selectionOnDrag selectionMode={SelectionMode.Partial} panOnDrag={[1,2]} panOnScroll panOnScrollSpeed={1} zoomOnScroll={false} zoomOnPinch><Background variant={undefined} color="#aeb4be" gap={14} size={1}/><MiniMap position="bottom-left" nodeColor="#6f3cff" maskColor="rgba(238,240,243,.75)"/><Controls position="bottom-left" orientation="horizontal"/></ReactFlow></section>
  </main>}
